### ISSUE TITLE
OAuth not working properly 

### ISSUE THREAD

**Issue by ArslanAfzalBhatti** [cbenard/SODailyMotionUpload#1]
Whenever I upload the videos it always uploaded from my own account. From this account I register my app at developer dailymotion and the video is alway uploaded from this account.
however i tried other accounts and give credentials at oauth screen bt the video uploaded at my account can you please tel me why it happens ?

**Comment by cbenard** [comment]
I don't understand what you're asking. I created it to answer a question on stackoverflow. It's not a program I use. I don't support it, so you'll need to fork it and make whatever changes you think are necessary. I will review pull requests if you send one.
